<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDy2RWg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDy2RWg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCDy2RWg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCDy2RWg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCDy2RWg\App_KernelProdContainer([
    'container.build_hash' => 'CDy2RWg',
    'container.build_id' => 'c80b22d5',
    'container.build_time' => 1753877666,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDy2RWg');
