<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
(require __DIR__.'/App_KernelProdContainer.php')->set(\ContainerCDy2RWg\App_KernelProdContainer::class, null);
require __DIR__.'/ContainerCDy2RWg/getServicesResetterService.php';
require __DIR__.'/ContainerCDy2RWg/getSecrets_VaultService.php';
require __DIR__.'/ContainerCDy2RWg/getSecrets_EnvVarLoaderService.php';
require __DIR__.'/ContainerCDy2RWg/getRouting_LoaderService.php';
require __DIR__.'/ContainerCDy2RWg/getErrorHandler_ErrorRenderer_HtmlService.php';
require __DIR__.'/ContainerCDy2RWg/getErrorControllerService.php';
require __DIR__.'/ContainerCDy2RWg/getDebug_ErrorHandlerConfiguratorService.php';
require __DIR__.'/ContainerCDy2RWg/getContainer_GetRoutingConditionServiceService.php';
require __DIR__.'/ContainerCDy2RWg/getContainer_EnvVarProcessorsLocatorService.php';
require __DIR__.'/ContainerCDy2RWg/getContainer_EnvVarProcessorService.php';
require __DIR__.'/ContainerCDy2RWg/getCache_SystemClearerService.php';
require __DIR__.'/ContainerCDy2RWg/getCache_SystemService.php';
require __DIR__.'/ContainerCDy2RWg/getCache_GlobalClearerService.php';
require __DIR__.'/ContainerCDy2RWg/getCache_AppClearerService.php';
require __DIR__.'/ContainerCDy2RWg/getCache_AppService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_VariadicService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_SessionService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_ServiceService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_RequestAttributeService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_RequestService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_QueryParameterValueResolverService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_DefaultService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_DatetimeService.php';
require __DIR__.'/ContainerCDy2RWg/getArgumentResolver_BackedEnumResolverService.php';
require __DIR__.'/ContainerCDy2RWg/getTemplateControllerService.php';
require __DIR__.'/ContainerCDy2RWg/getRedirectControllerService.php';
require __DIR__.'/ContainerCDy2RWg/getApplicationFacadeService.php';
require __DIR__.'/ContainerCDy2RWg/get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService.php';
require __DIR__.'/ContainerCDy2RWg/get_ServiceLocator_ZHyJIs5_KernelloadRoutesService.php';
require __DIR__.'/ContainerCDy2RWg/get_ServiceLocator_ZHyJIs5Service.php';

$classes = [];
$classes[] = 'Symfony\Bundle\FrameworkBundle\FrameworkBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ServiceLocator';
$classes[] = 'App\Facade\ApplicationFacade';
$classes[] = 'App\Greeting\GreetingService';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\BackedEnumValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DateTimeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\QueryParameterValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver';
$classes[] = 'Symfony\Component\Cache\Adapter\FilesystemAdapter';
$classes[] = 'Symfony\Component\Cache\Marshaller\DefaultMarshaller';
$classes[] = 'Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer';
$classes[] = 'Symfony\Component\Cache\Adapter\AdapterInterface';
$classes[] = 'Symfony\Component\Cache\Adapter\AbstractAdapter';
$classes[] = 'Symfony\Component\DependencyInjection\EnvVarProcessor';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\CacheAttributeListener';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\DebugHandlersListener';
$classes[] = 'Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ErrorController';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer';
$classes[] = 'Symfony\Component\EventDispatcher\EventDispatcher';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ErrorListener';
$classes[] = 'Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner';
$classes[] = 'Symfony\Component\Runtime\Runner\Symfony\ResponseRunner';
$classes[] = 'Symfony\Component\Runtime\SymfonyRuntime';
$classes[] = 'Symfony\Component\HttpKernel\HttpKernel';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver';
$classes[] = 'Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory';
$classes[] = 'App\Kernel';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\LocaleListener';
$classes[] = 'Symfony\Component\HttpKernel\Log\Logger';
$classes[] = 'Symfony\Component\HttpFoundation\RequestStack';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ResponseListener';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Routing\Router';
$classes[] = 'Symfony\Component\DependencyInjection\ParameterBag\ContainerBag';
$classes[] = 'Symfony\Component\Config\ResourceCheckerConfigCacheFactory';
$classes[] = 'Symfony\Component\Routing\RequestContext';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\RouterListener';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader';
$classes[] = 'Symfony\Component\Config\Loader\LoaderResolver';
$classes[] = 'Symfony\Component\Routing\Loader\XmlFileLoader';
$classes[] = 'Symfony\Component\HttpKernel\Config\FileLocator';
$classes[] = 'Symfony\Component\Routing\Loader\YamlFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\PhpFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\GlobFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\DirectoryLoader';
$classes[] = 'Symfony\Component\Routing\Loader\ContainerLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Routing\AttributeRouteControllerLoader';
$classes[] = 'Symfony\Component\Routing\Loader\AttributeDirectoryLoader';
$classes[] = 'Symfony\Component\Routing\Loader\AttributeFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\Psr4DirectoryLoader';
$classes[] = 'Symfony\Component\DependencyInjection\StaticEnvVarLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault';
$classes[] = 'Symfony\Component\String\LazyString';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ValidateRequestListener';

$preloaded = Preloader::preload($classes);
