<?php

namespace ContainerCDy2RWg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationFacadeService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Facade\ApplicationFacade' shared autowired service.
     *
     * @return \App\Facade\ApplicationFacade
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Facade\\ApplicationFacade'] = new \App\Facade\ApplicationFacade(new \App\Greeting\GreetingService());
    }
}
