<?php

namespace ContainerCDy2RWg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGreetingCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Commands\GreetingCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Commands\\GreetingCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('greeting:hello', ['greeting:hello'], 'Generate a greeting message for the given name', false, #[\Closure(name: 'App\\Commands\\GreetingCommand')] fn (): \App\Commands\GreetingCommand => ($container->privates['App\\Commands\\GreetingCommand'] ?? $container->load('getGreetingCommandService')));
    }
}
