<?php

namespace ContainerCDy2RWg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGreetingCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Commands\GreetingCommand' shared autowired service.
     *
     * @return \App\Commands\GreetingCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Commands\\GreetingCommand'] = $instance = new \App\Commands\GreetingCommand(($container->services['App\\Facade\\ApplicationFacade'] ?? $container->load('getApplicationFacadeService')));

        $instance->setName('greeting:hello');
        $instance->setAliases(['greeting:hello']);
        $instance->setDescription('Generate a greeting message for the given name');

        return $instance;
    }
}
